# Generated by Django 4.2.7 on 2025-05-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mixlyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradmin',
            old_name='Description',
            new_name='Message',
        ),
    ]
