# Generated by Django 4.2.7 on 2025-05-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mixlyapp', '0002_rename_description_useradmin_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Useradmin',
            new_name='customerdata',
        ),
    ]
