# Generated by Django 4.2.7 on 2025-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Momentodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificatename', models.CharField(max_length=25)),
                ('Position', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image')),
                ('Date', models.DateField()),
                ('description', models.TextField(max_length=150)),
            ],
        ),
    ]
